<a href="https://colab.research.google.com/github/Saiji/Data-Science-Work/blob/master/EDA2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/Generate Professor Data for Practice.csv")

In [ ]:
df

                    Name                 Rank  Experience  Age  Salary
0   Dr. Deborah Mitchell            Professor          32   65  195000
1      Dr. Lisa Thompson  Associate Professor          17   50  124000
2        Robert Williams  Assistant Professor           4   32   78000
3        Dr. Sarah Allen            Professor          31   64  190000
4         Jennifer Jones  Assistant Professor           2   29   71000
..                   ...                  ...         ...  ...     ...
95   Dr. Michelle Walker            Professor          21   53  151000
96    Dr. Cynthia Nelson  Associate Professor          10   41  101000
97      Alexander Foster  Assistant Professor           6   36   86500
98    Dr. Justin Roberts            Professor          20   52  148000
99   Dr. Christina Kelly  Associate Professor          10   41  102500

[100 rows x 5 columns]

In [ ]:
df.groupby('Rank').mean('Age')

                     Experience        Age         Salary
Rank
Assistant Professor    4.343750  33.250000   80937.500000
Associate Professor   13.352941  46.588235  113632.352941
Professor             25.705882  58.470588  169764.705882

In [ ]:
df['Salary']>90000

0      True
1      True
2     False
3      True
4     False
      ...
95     True
96     True
97    False
98     True
99     True
Name: Salary, Length: 100, dtype: bool

In [ ]:
df[df['Salary']>180000]

                    Name       Rank  Experience  Age  Salary
0   Dr. Deborah Mitchell  Professor          32   65  195000
3        Dr. Sarah Allen  Professor          31   64  190000
6     Dr. Cheryl Coleman  Professor          31   64  192000
9       Dr. Diane Cooper  Professor          30   63  188000
12    Dr. Patricia Brown  Professor          30   62  185000
15          Dr. Amy Cook  Professor          29   62  182000
18  Dr. Marilyn Gonzales  Professor          29   62  183000
21       Dr. Betty Perez  Professor          29   61  181000

In [4]:
df.head()

                   Name                 Rank  Experience  Age  Salary
0  Dr. Deborah Mitchell            Professor          32   65  195000
1     Dr. Lisa Thompson  Associate Professor          17   50  124000
2       Robert Williams  Assistant Professor           4   32   78000
3       Dr. Sarah Allen            Professor          31   64  190000
4        Jennifer Jones  Assistant Professor           2   29   71000

In [7]:
df.iloc[0]

Name          Dr. Deborah Mitchell
Rank                     Professor
Experience                      32
Age                             65
Salary                      195000
Name: 0, dtype: object

In [8]:
df

                    Name                 Rank  Experience  Age  Salary
0   Dr. Deborah Mitchell            Professor          32   65  195000
1      Dr. Lisa Thompson  Associate Professor          17   50  124000
2        Robert Williams  Assistant Professor           4   32   78000
3        Dr. Sarah Allen            Professor          31   64  190000
4         Jennifer Jones  Assistant Professor           2   29   71000
..                   ...                  ...         ...  ...     ...
95   Dr. Michelle Walker            Professor          21   53  151000
96    Dr. Cynthia Nelson  Associate Professor          10   41  101000
97      Alexander Foster  Assistant Professor           6   36   86500
98    Dr. Justin Roberts            Professor          20   52  148000
99   Dr. Christina Kelly  Associate Professor          10   41  102500

[100 rows x 5 columns]

In [9]:
df.iloc[-1]

Name          Dr. Christina Kelly
Rank          Associate Professor
Experience                     10
Age                            41
Salary                     102500
Name: 99, dtype: object

In [10]:
df.iloc[0:4]

                   Name                 Rank  Experience  Age  Salary
0  Dr. Deborah Mitchell            Professor          32   65  195000
1     Dr. Lisa Thompson  Associate Professor          17   50  124000
2       Robert Williams  Assistant Professor           4   32   78000
3       Dr. Sarah Allen            Professor          31   64  190000

In [11]:
df.iloc[:,0:2]

                    Name                 Rank
0   Dr. Deborah Mitchell            Professor
1      Dr. Lisa Thompson  Associate Professor
2        Robert Williams  Assistant Professor
3        Dr. Sarah Allen            Professor
4         Jennifer Jones  Assistant Professor
..                   ...                  ...
95   Dr. Michelle Walker            Professor
96    Dr. Cynthia Nelson  Associate Professor
97      Alexander Foster  Assistant Professor
98    Dr. Justin Roberts            Professor
99   Dr. Christina Kelly  Associate Professor

[100 rows x 2 columns]

In [13]:
df.iloc[0:2,]

                   Name                 Rank  Experience  Age  Salary
0  Dr. Deborah Mitchell            Professor          32   65  195000
1     Dr. Lisa Thompson  Associate Professor          17   50  124000

In [15]:
df.iloc[[0,3],[0,4]]

                   Name  Salary
0  Dr. Deborah Mitchell  195000
3       Dr. Sarah Allen  190000

In [30]:
df.iloc [0:10, 0:4]

                   Name                 Rank  Experience  Age
0  Dr. Deborah Mitchell            Professor          32   65
1     Dr. Lisa Thompson  Associate Professor          17   50
2       Robert Williams  Assistant Professor           4   32
3       Dr. Sarah Allen            Professor          31   64
4        Jennifer Jones  Assistant Professor           2   29
5      Dr. Alice Carter  Associate Professor          17   52
6    Dr. Cheryl Coleman            Professor          31   64
7           David Davis  Assistant Professor           5   33
8     Dr. Megan Jenkins  Associate Professor          17   52
9      Dr. Diane Cooper            Professor          30   63

In [20]:
df.head()

                   Name                 Rank  Experience  Age  Salary
0  Dr. Deborah Mitchell            Professor          32   65  195000
1     Dr. Lisa Thompson  Associate Professor          17   50  124000
2       Robert Williams  Assistant Professor           4   32   78000
3       Dr. Sarah Allen            Professor          31   64  190000
4        Jennifer Jones  Assistant Professor           2   29   71000

In [34]:
df.iloc[:,3:5]

    Age  Salary
0    65  195000
1    50  124000
2    32   78000
3    64  190000
4    29   71000
..  ...     ...
95   53  151000
96   41  101000
97   36   86500
98   52  148000
99   41  102500

[100 rows x 2 columns]

In [37]:
df.iloc[[59]]

                 Name       Rank  Experience  Age  Salary
59  Dr. Andrea Powell  Professor          25   58  168000

In [39]:
df.iloc[[0,2],[0,3]]

                   Name  Age
0  Dr. Deborah Mitchell   65
2       Robert Williams   32